---
# test.yml - version 0.4
#
- hosts: "{{ hosts }}" 
  
  tasks:
   - name: test
     action: command date
     ignore_errors: True
     register: result
     
   - name: echo
     action: command echo {{ result }}
